py_binary(
    name = "skeleton_client",
    srcs = [
        "skeleton_client.py",
        "skeleton_pb2.py",
    ],
    deps = [
        "//train:mnist_input_data",
        "@org_tensorflow//tensorflow:tensorflow_py",
    ],
)
