# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: skeleton.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='skeleton.proto',
  package='skeleton',
  syntax='proto3',
  serialized_pb=_b('\n\x0eskeleton.proto\x12\x08skeleton\"&\n\x0cMnistRequest\x12\x16\n\nimage_data\x18\x01 \x03(\x02\x42\x02\x10\x01\"\"\n\rMnistResponse\x12\x11\n\x05value\x18\x01 \x03(\x02\x42\x02\x10\x01\x32K\n\x0cMnistService\x12;\n\x08\x43lassify\x12\x16.skeleton.MnistRequest\x1a\x17.skeleton.MnistResponseb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MNISTREQUEST = _descriptor.Descriptor(
  name='MnistRequest',
  full_name='skeleton.MnistRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_data', full_name='skeleton.MnistRequest.image_data', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=66,
)


_MNISTRESPONSE = _descriptor.Descriptor(
  name='MnistResponse',
  full_name='skeleton.MnistResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='skeleton.MnistResponse.value', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=102,
)

DESCRIPTOR.message_types_by_name['MnistRequest'] = _MNISTREQUEST
DESCRIPTOR.message_types_by_name['MnistResponse'] = _MNISTRESPONSE

MnistRequest = _reflection.GeneratedProtocolMessageType('MnistRequest', (_message.Message,), dict(
  DESCRIPTOR = _MNISTREQUEST,
  __module__ = 'skeleton_pb2'
  # @@protoc_insertion_point(class_scope:skeleton.MnistRequest)
  ))
_sym_db.RegisterMessage(MnistRequest)

MnistResponse = _reflection.GeneratedProtocolMessageType('MnistResponse', (_message.Message,), dict(
  DESCRIPTOR = _MNISTRESPONSE,
  __module__ = 'skeleton_pb2'
  # @@protoc_insertion_point(class_scope:skeleton.MnistResponse)
  ))
_sym_db.RegisterMessage(MnistResponse)


_MNISTREQUEST.fields_by_name['image_data'].has_options = True
_MNISTREQUEST.fields_by_name['image_data']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_MNISTRESPONSE.fields_by_name['value'].has_options = True
_MNISTRESPONSE.fields_by_name['value']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class MnistServiceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Classify = channel.unary_unary(
        '/skeleton.MnistService/Classify',
        request_serializer=MnistRequest.SerializeToString,
        response_deserializer=MnistResponse.FromString,
        )


class MnistServiceServicer(object):

  def Classify(self, request, context):
    """Classifies image into digits.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MnistServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Classify': grpc.unary_unary_rpc_method_handler(
          servicer.Classify,
          request_deserializer=MnistRequest.FromString,
          response_serializer=MnistResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'skeleton.MnistService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaMnistServiceServicer(object):
  def Classify(self, request, context):
    """Classifies image into digits.
    """
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaMnistServiceStub(object):
  def Classify(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    """Classifies image into digits.
    """
    raise NotImplementedError()
  Classify.future = None


def beta_create_MnistService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  request_deserializers = {
    ('skeleton.MnistService', 'Classify'): MnistRequest.FromString,
  }
  response_serializers = {
    ('skeleton.MnistService', 'Classify'): MnistResponse.SerializeToString,
  }
  method_implementations = {
    ('skeleton.MnistService', 'Classify'): face_utilities.unary_unary_inline(servicer.Classify),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_MnistService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  request_serializers = {
    ('skeleton.MnistService', 'Classify'): MnistRequest.SerializeToString,
  }
  response_deserializers = {
    ('skeleton.MnistService', 'Classify'): MnistResponse.FromString,
  }
  cardinalities = {
    'Classify': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'skeleton.MnistService', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
