maven_jar(
    name = "hadoop_yarn_client",
    artifact = "org.apache.hadoop:hadoop-yarn-client:2.5.2",
)

maven_jar(
    name = "hadoop_yarn_api",
    artifact = "org.apache.hadoop:hadoop-yarn-api:2.5.2",
)

maven_jar(
    name = "hadoop_yarn_common",
    artifact = "org.apache.hadoop:hadoop-yarn-common:2.5.2",
)

maven_jar(
    name = "hadoop_common",
    artifact = "org.apache.hadoop:hadoop-common:2.5.2",
)

maven_jar(
    name = "commons_cli",
    artifact = "commons-cli:commons-cli:1.2",
)

maven_jar(
    name = "commons_io",
    artifact = "commons-io:commons-io:2.4",
)

maven_jar(
    name = "commons_lang",
    artifact = "commons-lang:commons-lang:2.6",
)

maven_jar(
    name = "commons_logging",
    artifact = "commons-logging:commons-logging:1.1.3"
)

maven_jar(
    name = "log4j",
    artifact = "log4j:log4j:1.2.17"
)

maven_jar(
    name = "guava",
    artifact = "com.google.guava:guava:11.0.2"
)

maven_jar(
    name = "commons_collections",
    artifact = "commons-collections:commons-collections:3.2.1"
)

maven_jar(
    name = "commons_configuration",
    artifact = "commons-configuration:commons-configuration:1.6"
)

maven_jar(
    name = "hadoop_auth",
    artifact = "org.apache.hadoop:hadoop-auth:2.5.2",
)

maven_jar(
    name = "hadoop_hdfs",
    artifact = "org.apache.hadoop:hadoop-hdfs:2.5.2"
)
maven_jar(
    name = "slf4j_api",
    artifact = "org.slf4j:slf4j-api:1.7.5",
)

maven_jar(
    name = "protobuf_java",
    artifact = "com.google.protobuf:protobuf-java:2.5.0",
)
